// api/src/modules/reports/pdf.generator.ts
// Pure Node.js PDF generation using pdfkit — no Python required
// Install: npm install pdfkit @types/pdfkit

import PDFDocument from 'pdfkit';

const TEAL   = '#0d9f9f';
const DARK   = '#0f172a';
const GRAY   = '#64748b';
const LIGHT  = '#f0fafa';
const WHITE  = '#ffffff';
const RED    = '#ef4444';
const GREEN  = '#22c55e';

const KES = (n: string | number) => `KES ${Number(n).toLocaleString('en-KE', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const PCT = (n: number) => `${n.toFixed(1)}%`;

// ─── HELPERS ──────────────────────────────────────────────────────────────────

function makePdf(): PDFDocument {
  return new PDFDocument({
    size: 'A4',
    margin: 40,
    info: { Creator: 'PropManager', Producer: 'PropManager' },
  });
}

function bufferPdf(doc: PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);
    doc.end();
  });
}

function header(doc: PDFDocument, title: string, subtitle: string, companyName: string) {
  // Teal header bar
  doc.rect(0, 0, doc.page.width, 70).fill(TEAL);
  doc.fillColor(WHITE).font('Helvetica-Bold').fontSize(18).text('PropManager', 40, 16);
  doc.fillColor('rgba(255,255,255,0.8)').font('Helvetica').fontSize(9).text(companyName, 40, 38);

  // Title on right
  doc.fillColor(WHITE).font('Helvetica-Bold').fontSize(13).text(title, 0, 18, { align: 'right', width: doc.page.width - 40 });
  doc.fillColor('rgba(255,255,255,0.8)').font('Helvetica').fontSize(9).text(subtitle, 0, 36, { align: 'right', width: doc.page.width - 40 });

  doc.moveDown(3.5);
}

function sectionTitle(doc: PDFDocument, text: string) {
  doc.moveDown(0.5);
  doc.fillColor(TEAL).font('Helvetica-Bold').fontSize(10).text(text.toUpperCase(), { characterSpacing: 0.5 });
  doc.moveDown(0.3);
}

function tableHeader(doc: PDFDocument, cols: { label: string; width: number; align?: string }[]) {
  const y = doc.y;
  const x = doc.x;
  const height = 20;
  const totalW = cols.reduce((s, c) => s + c.width, 0);

  doc.rect(x, y, totalW, height).fill(TEAL);
  let cx = x;
  cols.forEach(col => {
    doc.fillColor(WHITE).font('Helvetica-Bold').fontSize(8.5)
      .text(col.label, cx + 4, y + 5, { width: col.width - 8, align: (col.align ?? 'left') as any });
    cx += col.width;
  });
  doc.y = y + height;
}

function tableRow(doc: PDFDocument, cols: { value: string | number | null; width: number; align?: string }[], shade: boolean) {
  const y = doc.y;
  const x = doc.x;
  const height = 17;
  const totalW = cols.reduce((s, c) => s + c.width, 0);

  if (shade) doc.rect(x, y, totalW, height).fill(LIGHT);

  let cx = x;
  cols.forEach(col => {
    doc.fillColor(DARK).font('Helvetica').fontSize(8.5)
      .text(String(col.value ?? '—'), cx + 4, y + 4, { width: col.width - 8, align: (col.align ?? 'left') as any });
    cx += col.width;
  });

  // Bottom border
  doc.moveTo(x, y + height).lineTo(x + totalW, y + height).strokeColor('#e2e8f0').lineWidth(0.5).stroke();
  doc.y = y + height;
}

function summaryBox(doc: PDFDocument, items: { label: string; value: string; highlight?: boolean }[]) {
  const x = doc.x;
  const y = doc.y;
  const w = (doc.page.width - 80) / items.length;
  const h = 48;

  items.forEach((item, i) => {
    const bx = x + i * w;
    doc.rect(bx, y, w - 4, h).fill(item.highlight ? LIGHT : '#f8fafc');
    doc.fillColor(item.highlight ? TEAL : GRAY).font('Helvetica').fontSize(7.5)
      .text(item.label.toUpperCase(), bx + 8, y + 8, { width: w - 16 });
    doc.fillColor(item.highlight ? TEAL : DARK).font('Helvetica-Bold').fontSize(11)
      .text(item.value, bx + 8, y + 20, { width: w - 16 });
  });

  doc.y = y + h + 12;
}

function footerNote(doc: PDFDocument) {
  const y = doc.page.height - 30;
  doc.fillColor(GRAY).font('Helvetica').fontSize(7.5)
    .text(`Generated by PropManager · ${new Date().toLocaleString('en-KE')}`, 40, y, { align: 'center', width: doc.page.width - 80 });
}

// ─── MAIN EXPORT ─────────────────────────────────────────────────────────────

export async function generateReportPdf(data: any): Promise<Buffer> {
  switch (data.type) {
    case 'income-statement': return buildIncomeStatement(data);
    case 'rent-roll':        return buildRentRoll(data);
    case 'occupancy':        return buildOccupancy(data);
    case 'collection':       return buildCollection(data);
    default: throw new Error(`Unknown report type: ${data.type}`);
  }
}

// ─── INCOME STATEMENT ────────────────────────────────────────────────────────

async function buildIncomeStatement(data: any): Promise<Buffer> {
  const doc = makePdf();
  header(doc, 'Income Statement', `${data.fromDate} to ${data.toDate}`, data.companyName);

  // Summary boxes
  const netPositive = data.netIncome >= 0;
  summaryBox(doc, [
    { label: 'Total Revenue',  value: KES(data.revenue.total_revenue), highlight: true },
    { label: 'Total Expenses', value: KES(data.expTotals?.total_expenses ?? 0) },
    { label: 'Net Income',     value: KES(data.netIncome), highlight: netPositive },
  ]);

  // Revenue breakdown
  sectionTitle(doc, 'Revenue Breakdown');
  const revCols = [{ label: 'Category', width: 280 }, { label: 'Amount', width: 180, align: 'right' }];
  tableHeader(doc, revCols);

  const revItems = [
    ['Monthly Rent',       data.revenue.rent_revenue],
    ['Signing Bills',      data.revenue.signing_revenue],
    ['Penalties',          data.revenue.penalty_revenue],
    ['Adjustments',        data.revenue.adjustment_revenue],
  ];
  revItems.forEach(([label, val], i) => {
    tableRow(doc, [{ value: label as string, width: 280 }, { value: KES(val as number), width: 180, align: 'right' }], i % 2 === 0);
  });

  // Total row
  doc.moveDown(0.2);
  const ty = doc.y;
  doc.rect(doc.x, ty, 460, 18).fill(LIGHT);
  doc.fillColor(TEAL).font('Helvetica-Bold').fontSize(9)
    .text('TOTAL REVENUE', doc.x + 4, ty + 4, { width: 276 });
  doc.text(KES(data.revenue.total_revenue), doc.x + 280, ty + 4, { width: 176, align: 'right' });
  doc.y = ty + 22;

  // Expenses
  if (data.expenses?.length) {
    doc.moveDown(0.8);
    sectionTitle(doc, 'Expenses');
    const expCols = [{ label: 'Category', width: 200 }, { label: 'Description', width: 150 }, { label: 'Amount', width: 110, align: 'right' }];
    tableHeader(doc, expCols);
    data.expenses.forEach((e: any, i: number) => {
      tableRow(doc, [
        { value: e.category, width: 200 },
        { value: e.description ?? '—', width: 150 },
        { value: KES(e.amount), width: 110, align: 'right' },
      ], i % 2 === 0);
    });

    doc.moveDown(0.2);
    const ety = doc.y;
    doc.rect(doc.x, ety, 460, 18).fill('#fee2e2');
    doc.fillColor(RED).font('Helvetica-Bold').fontSize(9)
      .text('TOTAL EXPENSES', doc.x + 4, ety + 4, { width: 346 });
    doc.text(KES(data.expTotals?.total_expenses ?? 0), doc.x + 350, ety + 4, { width: 106, align: 'right' });
    doc.y = ety + 22;
  }

  // Net income
  doc.moveDown(0.8);
  const ny = doc.y;
  const netBg = netPositive ? '#dcfce7' : '#fee2e2';
  const netColor = netPositive ? GREEN : RED;
  doc.rect(doc.x, ny, 460, 24).fill(netBg);
  doc.fillColor(netColor).font('Helvetica-Bold').fontSize(11)
    .text('NET INCOME', doc.x + 4, ny + 6, { width: 346 });
  doc.text(KES(data.netIncome), doc.x + 350, ny + 6, { width: 106, align: 'right' });

  footerNote(doc);
  return bufferPdf(doc);
}

// ─── RENT ROLL ────────────────────────────────────────────────────────────────

async function buildRentRoll(data: any): Promise<Buffer> {
  const doc = makePdf();
  header(doc, 'Rent Roll', `As of ${data.asOf}`, data.companyName);

  const occupied = data.rows.filter((r: any) => r.tenant_name).length;
  const totalRent = data.rows.reduce((s: number, r: any) => s + (r.tenant_name ? Number(r.monthly_rent) : 0), 0);

  summaryBox(doc, [
    { label: 'Total Units', value: String(data.rows.length) },
    { label: 'Occupied',    value: String(occupied), highlight: true },
    { label: 'Vacant',      value: String(data.rows.length - occupied) },
    { label: 'Total Rent',  value: KES(totalRent), highlight: true },
  ]);

  const cols = [
    { label: 'Property',   width: 100 },
    { label: 'Unit',       width: 42 },
    { label: 'Tenant',     width: 120 },
    { label: 'Phone',      width: 80 },
    { label: 'Rent (KES)', width: 78, align: 'right' },
    { label: 'Start',      width: 60 },
    { label: 'Status',     width: 55 },
  ];

  tableHeader(doc, cols);

  data.rows.forEach((r: any, i: number) => {
    tableRow(doc, [
      { value: r.property_name,      width: 100 },
      { value: r.unit_number,        width: 42 },
      { value: r.tenant_name ?? 'Vacant', width: 120 },
      { value: r.phone ?? '—',       width: 80 },
      { value: r.tenant_name ? KES(r.monthly_rent) : '—', width: 78, align: 'right' },
      { value: r.start_date ?? '—',  width: 60 },
      { value: r.tenant_name ? 'Occupied' : 'Vacant', width: 55 },
    ], i % 2 === 0);
  });

  footerNote(doc);
  return bufferPdf(doc);
}

// ─── OCCUPANCY ────────────────────────────────────────────────────────────────

async function buildOccupancy(data: any): Promise<Buffer> {
  const doc = makePdf();
  header(doc, 'Occupancy Report', `As of ${data.asOf}`, data.companyName);

  const t = data.totals;
  const overallRate = Number(t.total_units) > 0 ? (Number(t.occupied) / Number(t.total_units)) * 100 : 0;

  summaryBox(doc, [
    { label: 'Total Units',    value: String(t.total_units) },
    { label: 'Occupied',       value: String(t.occupied), highlight: true },
    { label: 'On Notice',      value: String(t.on_notice) },
    { label: 'Vacant',         value: String(t.vacant) },
    { label: 'Occupancy Rate', value: PCT(overallRate), highlight: true },
  ]);

  const cols = [
    { label: 'Property',      width: 160 },
    { label: 'Total',         width: 50,  align: 'right' },
    { label: 'Occupied',      width: 60,  align: 'right' },
    { label: 'Notice',        width: 50,  align: 'right' },
    { label: 'Vacant',        width: 50,  align: 'right' },
    { label: 'Occ. Rate',     width: 60,  align: 'right' },
    { label: 'Actual Rent',   width: 85,  align: 'right' },
  ];

  tableHeader(doc, cols);

  data.byProperty.forEach((p: any, i: number) => {
    const rate = Number(p.total_units) > 0 ? (Number(p.occupied) / Number(p.total_units)) * 100 : 0;
    tableRow(doc, [
      { value: p.property_name, width: 160 },
      { value: p.total_units,   width: 50,  align: 'right' },
      { value: p.occupied,      width: 60,  align: 'right' },
      { value: p.on_notice,     width: 50,  align: 'right' },
      { value: p.vacant,        width: 50,  align: 'right' },
      { value: PCT(rate),       width: 60,  align: 'right' },
      { value: KES(p.actual_rent), width: 85, align: 'right' },
    ], i % 2 === 0);
  });

  footerNote(doc);
  return bufferPdf(doc);
}

// ─── COLLECTION ───────────────────────────────────────────────────────────────

async function buildCollection(data: any): Promise<Buffer> {
  const doc = makePdf();
  header(doc, 'Payment Collection Report', data.forMonth.slice(0, 7), data.companyName);

  const s = data.summary;
  summaryBox(doc, [
    { label: 'Total Billed',      value: KES(s.total_billed) },
    { label: 'Collected',         value: KES(s.total_collected), highlight: true },
    { label: 'Outstanding',       value: KES(s.total_outstanding) },
    { label: 'Collection Rate',   value: `${data.collectionRate}%`, highlight: true },
  ]);

  const cols = [
    { label: 'Tenant',     width: 120 },
    { label: 'Unit',       width: 45 },
    { label: 'Property',   width: 110 },
    { label: 'Billed',     width: 75,  align: 'right' },
    { label: 'Paid',       width: 75,  align: 'right' },
    { label: 'Balance',    width: 75,  align: 'right' },
    { label: 'Status',     width: 55 },
  ];

  tableHeader(doc, cols);

  data.rows.forEach((r: any, i: number) => {
    tableRow(doc, [
      { value: r.tenant_name,   width: 120 },
      { value: r.unit_number,   width: 45 },
      { value: r.property_name, width: 110 },
      { value: KES(r.total_amount), width: 75, align: 'right' },
      { value: KES(r.total_paid),   width: 75, align: 'right' },
      { value: KES(r.total_due),    width: 75, align: 'right' },
      { value: r.status,        width: 55 },
    ], i % 2 === 0);
  });

  footerNote(doc);
  return bufferPdf(doc);
}